create database clg;
use clg;
create table students(Roll_no int,fname varchar(20),lname varchar (20),gender varchar(2),city varchar(20),year varchar(20),percentage int,branch varchar(10),category varchar(30),university varchar(20),ADMQUOTA varchar(20),ADMyear varchar(90));
insert into students values(1,'Nitin','Sharma','m','Solapur','BE',70,'ENTC','GENERAL','HOME','CAP',2008);
insert into students values(2,'Ameet','Kumar','m','pune','TE',75,'Ele','General','HOME','CAP',2007);
insert into students values(3,'Neha','Patil','f','satara','FE',72,'CSE','General','Other','Institute',2010);
insert into students values(4,'amol','Kshirsagar','m','mumbai','SE',88,'IT','OBC','other','CAP',2009);
insert into students values(5,'Komal','Deshmukh','f','solapur','TE',70,'MEch','General','other','CAP',2012);
insert into students values(6,'Mughda','Patil','f','osmanabad','BE',85,'ENTC','SC','Other','institute',2014);
select * from students where ADMyear>2010;
select * from students where ADMQUOTA in ('CAP');
select  branch, fname , city, ADMyear from students where gender='f';
select branch , fname ,city , category from students where category='general' ;
select  fname ,city , branch , category , percentage from students where percentage>=75;
select fname , branch , percentage , ADMQUOTA from students where university= 'other' and ADMQUOTA='INSTITUTE';
select fname,branch,percentage,category,gender,city from students where gender='m'and city='solapur';
select fname,branch,percentage,category,gender,city from students where gender='m' and city='solapur'or city='pune';
select fname,branch,ADMyear,percentage from students where percentage between 70 and 85 ;
select fname,branch,ADMyear,category from students where ADMyear>2010 or branch='Ele' or branch='ENTC';
select* from students order by percentage desc;
select fname,count(*) from students group by fname;
select * from students where fname like ('%i_');
select*from students where fname like ('_u%');
select * from students where fname like ('__m%') or fname like ('%m');